{% set name = "sen2nbar" %}
{% set version = "2023.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sen2nbar-{{ version }}.tar.gz
  sha256: 33aed99313bbbde5b7fa2600fa9c59ab836be8a7089a07f200e4a11c6f6801b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - cubo >=2023.7.0
    - pystac
    - rasterio >=1.3.6
    - requests
    - rioxarray >=0.13.4
    - scipy >=1.10.1
    - tqdm
    - xmltodict

test:
  imports:
    - sen2nbar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ESDS-Leipzig/sen2nbar
  summary: Nadir BRDF Adjusted Reflectance (NBAR) for Sentinel-2 in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://cubo.readthedocs.io/en/latest/
  dev_url: https://github.com/ESDS-Leipzig/sen2nbar

extra:
  recipe-maintainers:
    - davemlz
